TexnoGallery/Areas/Admin/Controllers/AboutSiteController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TexnoGallery.Models;

namespace TexnoGallery.Areas.Admin.Controllers
{
    [AuthenticationFilter]
    public class AboutSiteController : Controller
    {
        private TexnoGalleryEntities db = new TexnoGalleryEntities();

        // GET: Admin/AboutSite
        public ActionResult Index()
        {
            return View(db.AboutUs.ToList());
        }





        // GET: Admin/AboutSite/Edit/5

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AboutU aboutUs = db.AboutUs.Find(id);
            if (aboutUs == null)
            {
                return HttpNotFound();
            }
            return View(aboutUs);
        }

        // POST: Admin/AboutSite/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Edit([Bind(Include = "Id,Title,Description,AboutImage")] AboutU aboutUs)
        {
            if (ModelState.IsValid)
            {
                db.Entry(aboutUs).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(aboutUs);
        }

      

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TexnoGallery/Areas/Admin/Views/AboutSite/Edit.cshtml
@model TexnoGallery.Models.AboutU

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <h4>AboutUs</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <form method="post">
                    <textarea id="Description" name="Description">Hello, World!</textarea>
                </form>
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AboutImage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AboutImage, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AboutImage, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

TexnoGallery/Areas/Admin/Views/AboutSite/Index.cshtml
@model IEnumerable<TexnoGallery.Models.AboutU>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
@section adminCss{
    <link rel="stylesheet" href="~/Areas/Admin/assets/css/photoswipe.css">
}
<h2 class="text-center mt-3">About Us</h2>

@foreach (var item in Model)
{
    <div class="my-gallery card-body row gallery-with-description">
        <figure class="col-xl-3 col-sm-6">
            <img src="~/Uploads/@item.AboutImage" itemprop="thumbnail" alt="Image description">
            <div class="caption" style="border: 1px solid #e4e6ee;padding: 5px 10px 10px 10px;border-top: none !important;">
                <h4>@item.Title</h4>
                <p>@item.Description</p>
                <div class="text-center">
                    <a class="btn btn-primary btn-sm" name="Edit" href=@Url.Action("Edit","AboutSite",new { id=item.Id})>
                        <i class="far fa-edit"></i> Edit
                    </a>
                </div>
            </div>
        </figure>
    </div>
}