TexnoGallery/Controllers/MainAccountController.cs
using System;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using TexnoGallery.Models;
using TexnoGallery.ViewModel.Default;

namespace TexnoGallery.Controllers
{
   
    public class MainAccountController : Controller
    {

        TexnoGalleryEntities db = new TexnoGalleryEntities();
        public ActionResult Profiles()
        {
            ApplicationUser appUser = Session["user"] as ApplicationUser;
            if (appUser == null) return RedirectToAction("index","home");
            var defaultModel = new DefaultViewModel
            {
                CategoryName = db.Categories.ToList(),
                applicationUser=appUser 
            };

            return View(defaultModel);
        }
        [HttpPost]
        public async Task<JsonResult>  GetPassword(string password, string newpassword,string confirmpassword)
        {
            if (password!="" && newpassword!="" && confirmpassword!="")
            {
            object data = null;
            ApplicationUser userpass = Session["user"] as ApplicationUser;
            if (userpass != null)
            {
                if (Crypto.VerifyHashedPassword(userpass.Password,password ))
                {
                    userpass.Password =userpass.ConfirmPassword= Crypto.HashPassword(newpassword);
                    await db.SaveChangesAsync();
                    data = new {
                        status = 200,
                        message = "Success",
                    };
                    return Json(data, JsonRequestBehavior.AllowGet);

                }

            }
            }

            return Json(false, JsonRequestBehavior.AllowGet);

        }
        public ActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Register(ApplicationUser us, HttpPostedFileBase Photo)
        {
            if (!ModelState.IsValid) return View(us);

            if (Photo != null)  
            {

                WebImage image = new WebImage(Photo.InputStream);
                FileInfo photoInfo = new FileInfo(Photo.FileName);
                string newPhoto = Guid.NewGuid().ToString() + photoInfo.Extension;
                image.Save("~/Uploads/UserImage/" + newPhoto);
                us.ProfileImage = "/Uploads/UserImage/" + newPhoto;
            }

            if (db.ApplicationUsers.Any(u => u.Email == us.Email))
            {
                ModelState.AddModelError("Email", "This email is duplicate");
                return View(us);
            }

            if (db.ApplicationUsers.Any(u => u.UserName == us.UserName))
            {
                ModelState.AddModelError("Email", "This username is duplicate");
                return View(us);
            }

            us.Password = us.ConfirmPassword = Crypto.HashPassword(us.Password);

            db.ApplicationUsers.Add(us);
            await db.SaveChangesAsync();

            return RedirectToAction(nameof(Login));
        }
        public ActionResult Login()
        {
            
            return View();
        }
        [HttpPost]
        
        public ActionResult Login(UserLogin loginUser)
        {
            if (!ModelState.IsValid) return View(loginUser);

            ApplicationUser appUser = db.ApplicationUsers.FirstOrDefault(u => u.Email == loginUser.Email);

            if (appUser == null)
            {
                ModelState.AddModelError("summary", "Email or password is invalid");
                return View(loginUser);
            }

            if (!Crypto.VerifyHashedPassword(appUser.Password, loginUser.Password))
            {
                ModelState.AddModelError("summary", "Email or password is invalid");
                return View(loginUser);
            }

            Session["user"] = appUser;

            return RedirectToAction("Index", "Home");
        }
           
        public ActionResult Logout()
        {
            Session.Clear();
            return RedirectToAction("Index", "Home");
        }


    }
}

TexnoGallery/Views/MainAccount/Profiles.cshtml
@using TexnoGallery.ViewModel.Default
@model DefaultViewModel

@{
    ViewBag.Title = "Profiles";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">

    <div class="row mt-5">

        <div class="col-lg-3">
            <div class="leftBox p-3">
                <h4 class="text-secondary  mb-3">Mənim seçimlərim</h4>
                <ul class="list-unstyled">
                    <li data-ng-class="settings" class="chActive"><a href="#/settings"> Mənim məlumatlarım</a></li>
                    <li data-ng-class="changePassword"><a href="#/change-password">Şifrəni yeniləmək</a></li>
                </ul>
            </div>
        </div>
        <div class="col-lg-9">
            <div class="header-profile ">
                <h2>Mənim məlumatlarım</h2>
            </div>
            <hr />
            <form id="prof-form" method="post" class="form">
                <div id="settings" class="form-set">
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="name" >Ad <span>*</span></label>
                                <input type="text" value="@Model.applicationUser.FirstName" class="form-control">
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="lastname" class="font-noto-s">Soyad <span>*</span></label>
                                <input type="text" value="@Model.applicationUser.LastName" id="lastname" class="form-control">
                            </div>
                        </div>
                        @*<div class="col-md-4">
                            <div class="form-group">
                                <label for="father_name" class="font-noto-s">Atasının adı <span>*</span></label>
                                <input type="text" id="father_name" class="font-noto-s form-control ng-pristine ng-untouched ng-valid ng-empty" data-ng-model="form.data.father_name">
                            </div>
                        </div>*@
                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="email" class="font-noto-s">
                                    Elektron poçt <span>*</span>
                                </label>
                                <input value="@Model.applicationUser.Email" type="email" class="form-control">
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="shopName" class="font-noto-s"> Mobil telefon <span>*</span></label>
                                <input type="text" class=" form-control" disabled="" />
                            </div>
                        </div>

                        @*<div class="col-md-2">
                            <div class="form-group" id="bd">
                                <label for="date" class="font-noto-s">Doğum günü</label>
                                <input type="text" class="form-control dateInput ng-valid ng-touched ng-not-empty ng-dirty ng-valid-parse" date-picker="" name="birthday" data-ng-model="form.data.birthday" id="date">
                                <label for="date">
                                    <img src="https://shop.az/site/img/calendar.png" class="dateIcon" alt="">
                                </label>
                            </div>
                        </div>*@
                    </div>
                    <div class="row">
                        <div class="col-md-6 mb-5">
                            <div class="clearfix text-right">
                                <button class="btn btn-success" data-ng-click="form.submit()">
                                    <span>Yadda saxla</span>
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
                <div id="changePassword" class="form-set d-none">
                            <div class="">
                                <h3>Şifrəni yeniləmək</h3>
                            </div>
                        <div class="row ng-scope">
                            <div class="col-md-3">
                                <div class="form-group">
                                    <label for="oldpass">Şifrə</label>
                                    <input type="password" id="oldpass" class="font-noto-s form-control ng-pristine ng-untouched ng-valid ng-empty" data-ng-model="form.data.old" autocomplete="off">
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-3">
                                <div class="form-group">
                                    <label for="NEWpassword">Yeni şifrə</label>
                                    <input type="password" id="NEWpassword" class=" form-control "  autocomplete="off">
                                </div>
                            </div>
                            <div class="col-md-3">
                                <div class="form-group">
                                    <label for="confirmpassword">Yeni şifrəni təkrarla</label>
                                    <input type="password" id="confirmpassword" class="form-control " autocomplete="off">
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-3">
                                <button data-ng="forgotPsw" type="submit" class=" mb-4 btn btn-warning" >Yadda saxla </button>
                            </div>
                        </div>
                    </div>
            </form>
            
        </div>
    </div>
</div>

@section mainJs{
        <script src="~/FrontPublic/js/tilt.jquery.js" type="text/javascript"></script>
        <script src="~/FrontPublic/js/jquery.counterup.min.js"></script>
        <script src="~/FrontPublic/js/owl.carousel.js" type="text/javascript"></script>
        <script src="~/FrontPublic/js/main.js"></script>
        <script>
            $("#prof-form").on('submit', function () {
                let oldpassword = $("#oldpass").val();
                let newpass = $("#NEWpassword").val();
                let confirmpass = $("#confirmpassword").val();
                $.ajax({
                    
                    type: "POST",
                    url: "@Url.Action("GetPassword","MainAccount")",
                    data: {
                         'password': oldpassword, 'newpassword': newpass,
                        'confirmpassword': confirmpass
                    },
                    datatype: "JSON",
                    success: function (res) {
                        console.log(res)
                    }
                })
    })
        </script>
}